### ISSUE TITLE
Erro nos testes

### ISSUE THREAD

**Issue by renanbastos93** [lagden/placa#1]
Dei fork no projeto com intuição de tentar ajudar em algo, ver o que posos incrementar, aí fui rodar os testes pelo `npm test` e deu varios erro. Que posso estar errando?
Nota: dei npm install antes!

![image](https://user-images.githubusercontent.com/8202898/35896110-c911aef8-0ba1-11e8-8005-1ee53934ebf0.png)

**Comment by lagden** [comment]
é problema no seu git....
vc esta convertendo o LF para CRLF...

deixa seu git config assim:

git config --global core.autocrlf false


isso evita esse problema

2018-02-07 0:57 GMT-02:00 RENAN.BASTOS <notifications@github.com>:

**Comment by lagden** [comment]
Mais informações em: https://git-scm.com/book/pt-br/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace

Vou fechar a issue, mas fique a vontade para tirar dúvidas ou comentar...

**Comment by lagden** [comment]
@renanbastos93 pode testar no NPM

https://runkit.com/lagden/5a7bae982ba3520012358c58

**Comment by renanbastos93** [comment]
Sim pelo NPM eu teste, mas quero testar os seus testes, e continua o erro, então isso me diz que a LIB não é bem segura, fiz o que você disse, e uma dúvida pq usou xo pra teste e não mocha outras lib?

**Comment by lagden** [comment]
o xo não é para teste... ele o lint: https://github.com/sindresorhus/xo
o teste é feito com ava: https://github.com/avajs/ava
