### ISSUE TITLE
(...)

### ISSUE THREAD

**Issue by enigma-watcher** [lagden/placa#11]
![screenshot_20180813-101320_sinesp cidadao](https://user-images.githubusercontent.com/42346260/44036503-4cd207d6-9ee8-11e8-9222-bf7a57400928.jpg)

**Comment by lagden** [comment]
Mas não estamos acessando o banco de dados deles.
Estamos acessando a API aberta deles, logo eles que estão divulgando.

Aqui, nada é comercializado e nem armazenado...

E também estes dados deveriam ser de domínio público, já que somos nós que pagamos por ele (impostos).
